[project]
name = "tfg-evosymbolic"
version = "0.1.0"
description = "tfg-evosymbolic project"
readme = "README.md"
requires-python = ">=3.12, <3.13"
dependencies = [
    "matplotlib>=3.10.3",
    "numpy>=2.3.0",
    "prettytable>=3.16.0",
    "progress>=1.6",
    "sympy>=1.14.0",
]
